export function splitList(value: string): string[] {
  return value
    .split(/[,;\n]/)
    .map((x)=>x.trim().replace(/^[\s\-–—•·✓✔]+/,"").trim())
    .filter(Boolean);
}
export function normalize(value:string):string{return value.toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/[’']/g," ").replace(/[^a-z0-9+#.\s-]/g," ").replace(/\s+/g," ").trim();}
type SkillGroup={label:string;aliases:string[]};
export const SKILL_GROUPS:SkillGroup[]=[
{label:"Intelligence artificielle générative",aliases:["intelligence artificielle generative","ia generative","genai","generative ai"]},{label:"Automatisation des processus",aliases:["automatisation des processus","automatisation de processus","automatisation","workflow automatise","workflows automatises","automation"]},{label:"Analyse des besoins métiers",aliases:["analyse des besoins metiers","recueil des besoins","besoins metiers","cadrage fonctionnel","expression des besoins"]},{label:"Assistants / Agents IA",aliases:["assistant ia","assistants ia","agent ia","agents ia","assistant conversationnel"]},{label:"Gestion de projet digital",aliases:["gestion de projet digital","chef de projet digital","cheffe de projet digital","pilotage de projets web","pilotage de projet digital","product owner"]},{label:"n8n",aliases:["n8n"]},{label:"API REST",aliases:["api rest","rest api"]},{label:"OpenAI / LLM",aliases:["openai","llm","large language model","gpt"]},{label:"TypeScript",aliases:["typescript"]},{label:"JavaScript",aliases:["javascript"]},{label:"Next.js",aliases:["next.js","nextjs"]},{label:"React",aliases:["react"]},{label:"Node.js",aliases:["node.js","nodejs"]},{label:"Python",aliases:["python"]},{label:"Java",aliases:["java developer","java spring","java jee","java/j2ee"]},{label:"PHP",aliases:["php"]},{label:"Salesforce",aliases:["salesforce"]},{label:"SAP",aliases:["sap"]},{label:"SEO",aliases:["seo","referencement naturel"]},{label:"GEO",aliases:["generative engine optimization","optimisation geo"]},{label:"Google Ads",aliases:["google ads","adwords"]},{label:"HubSpot",aliases:["hubspot"]},{label:"CRM",aliases:["crm"]},{label:"Power BI",aliases:["power bi","powerbi"]},{label:"SQL",aliases:["sql"]},{label:"AWS",aliases:["aws","amazon web services"]},{label:"Azure",aliases:["azure"]},{label:"Docker",aliases:["docker"]},{label:"Kubernetes",aliases:["kubernetes"]},{label:"Figma",aliases:["figma"]},{label:"SaaS B2B",aliases:["saas b2b","saas"]},{label:"Anglais professionnel",aliases:["anglais professionnel","anglais courant","anglais fluent","english professional","professional english","fluent english"]}];
const NEGATION_PATTERNS=[/aucune?\s+(?:experience|pratique|maitrise)/,/pas\s+d\s+(?:experience|expertise|pratique)/,/sans\s+(?:experience|expertise|pratique|maitrise)/,/experience\s+(?:limitee|faible|minimale)/,/notions?\s+(?:seulement|uniquement)/,/(?:non|peu)\s+(?:maitrise|experimente|experimentee|operationnel|operationnelle)/,/veille\s+(?:sur|autour de)/];
function isWordChar(ch:string|undefined){return !!ch&&/[a-z0-9]/i.test(ch)}
function occurrences(text:string,needle:string){const out:number[]=[];let start=0;while(true){const i=text.indexOf(needle,start);if(i<0)break;const before=text[i-1],after=text[i+needle.length];if(!isWordChar(before)&&!isWordChar(after))out.push(i);start=i+Math.max(1,needle.length)}return out}
export function aliasEvidence(rawText:string,aliasRaw:string){const text=` ${normalize(rawText)} `;const alias=normalize(aliasRaw);if(!alias)return{positive:false,negated:false};const hits=occurrences(text,alias);if(!hits.length)return{positive:false,negated:false};let negated=false;for(const idx of hits){const before=text.slice(Math.max(0,idx-90),idx);const after=text.slice(idx+alias.length,Math.min(text.length,idx+alias.length+55));if(NEGATION_PATTERNS.some(p=>p.test(`${before} ${after}`)))negated=true;else return{positive:true,negated}}return{positive:false,negated}}
export function detectSkills(rawText:string){return SKILL_GROUPS.filter(({aliases})=>aliases.some(a=>aliasEvidence(rawText,a).positive)).map(x=>x.label)}
export function detectNegatedSkills(rawText:string){return SKILL_GROUPS.filter(({aliases})=>{const e=aliases.map(a=>aliasEvidence(rawText,a));return e.some(x=>x.negated)&&!e.some(x=>x.positive)}).map(x=>x.label)}
function cleanLine(s:string){return s.replace(/[•|]+/g," ").replace(/\s+/g," ").trim()}
function looksLikeName(s:string){const x=cleanLine(s);if(x.length<4||x.length>70||/@|https?:|www\.|\d{4,}/i.test(x))return false;const words=x.split(/\s+/);if(words.length<2||words.length>5)return false;return words.every(w=>/^[A-Za-zÀ-ÖØ-öø-ÿ'’-]+$/.test(w))}
function extractName(raw:string,email:string){const lines=raw.split(/\r?\n/).map(cleanLine).filter(Boolean).slice(0,18);const direct=lines.find(looksLikeName);if(direct)return direct;if(email){const local=email.split("@")[0].replace(/[._-]+/g," ");if(local.split(" ").length>=2)return local.replace(/\b\w/g,c=>c.toUpperCase())}return "Candidat importé"}
function extractLocation(raw:string){const lines=raw.split(/\r?\n/).map(cleanLine).filter(Boolean).slice(0,25);for(const line of lines){const m=line.match(/(?:localisation|location|ville|adresse)\s*[:\-]\s*([^|•,]{2,60})/i);if(m)return cleanLine(m[1]);}const known=["Paris","Lyon","Marseille","Toulouse","Bordeaux","Lille","Nantes","Strasbourg","Rennes","Montpellier","Boulogne-Billancourt","Levallois-Perret","Versailles","Antony","Metz"];for(const city of known)if(new RegExp(`\\b${city.replace("-","[- ]")}\\b`,"i").test(lines.join(" ")))return city;return ""}
function estimateYearsFromRanges(raw:string){
 const currentYear=new Date().getFullYear();const ranges=[...raw.matchAll(/\b(19\d{2}|20\d{2})\s*[-–—]\s*(19\d{2}|20\d{2}|present|présent|aujourd'hui|aujourd’hui|current)\b/gi)];
 if(!ranges.length)return null;const intervals=ranges.map(m=>{const start=Number(m[1]);const end=/^\d{4}$/.test(m[2])?Number(m[2]):currentYear;return[start,Math.max(start,Math.min(end,currentYear))] as [number,number]}).filter(([s,e])=>s>=1980&&e>=s&&e-s<=20);
 if(!intervals.length)return null;intervals.sort((a,b)=>a[0]-b[0]);const merged:[number,number][]=[];for(const it of intervals){const last=merged[merged.length-1];if(!last||it[0]>last[1])merged.push([...it] as [number,number]);else last[1]=Math.max(last[1],it[1]);}const total=merged.reduce((sum,[s,e])=>sum+(e-s),0);return total>0?Math.min(45,total):null;
}
export function extractCandidate(rawText:string){const compact=rawText.replace(/\s+/g," ").trim();const email=compact.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]??"";const yearsMatches=[...compact.matchAll(/(\d{1,2})\s*(?:ans|annees|années)\s+(?:d['’]?experience|d’expérience|d'experience)/gi)].map(m=>Number(m[1])).filter(Number.isFinite);const explicitYears=yearsMatches.length?Math.max(...yearsMatches):null;const rangeYears=estimateYearsFromRanges(rawText);const years=explicitYears??rangeYears;const skills=detectSkills(compact);const summary=compact.length>650?compact.slice(0,650)+"…":compact;return{fullName:extractName(rawText,email),location:extractLocation(rawText),email,years,skills,summary}}
