export function splitList(value: string): string[] {
  return value
    .split(/[,;\n]/)
    .map((x)=>x.trim().replace(/^[\s\-–—•·✓✔]+/,"").trim())
    .filter(Boolean);
}
export function normalize(value:string):string{return value.toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/[’']/g," ").replace(/[^a-z0-9+#.\s-]/g," ").replace(/\s+/g," ").trim();}
type SkillGroup={label:string;aliases:string[]};

// Référentiel transversal Host Talent AI.
// Il décrit des compétences observables et non des secteurs imposés au cabinet.
// Les études de marché restent une couche indépendante dans externalMarketTrends.ts.
export const SKILL_GROUPS:SkillGroup[]=[
// Digital, IT, data, IA
{label:"Intelligence artificielle générative",aliases:["intelligence artificielle generative","ia generative","genai","generative ai"]},{label:"Automatisation des processus",aliases:["automatisation des processus","automatisation de processus","automatisation","workflow automatise","workflows automatises","automation"]},{label:"Analyse des besoins métiers",aliases:["analyse des besoins metiers","recueil des besoins","besoins metiers","cadrage fonctionnel","expression des besoins"]},{label:"Assistants / Agents IA",aliases:["assistant ia","assistants ia","agent ia","agents ia","assistant conversationnel"]},{label:"Gestion de projet digital",aliases:["gestion de projet digital","chef de projet digital","cheffe de projet digital","pilotage de projets web","pilotage de projet digital","product owner"]},{label:"Product management",aliases:["product manager","product management","product owner","roadmap produit","strategie produit"]},{label:"UX / UI",aliases:["ux","ui design","ux design","user experience","experience utilisateur","design system"]},{label:"n8n",aliases:["n8n"]},{label:"API REST",aliases:["api rest","rest api"]},{label:"OpenAI / LLM",aliases:["openai","llm","large language model","gpt"]},{label:"TypeScript",aliases:["typescript"]},{label:"JavaScript",aliases:["javascript"]},{label:"Next.js",aliases:["next.js","nextjs"]},{label:"React",aliases:["react"]},{label:"Node.js",aliases:["node.js","nodejs"]},{label:"Python",aliases:["python"]},{label:"Java",aliases:["java developer","java spring","java jee","java/j2ee"]},{label:"PHP",aliases:["php"]},{label:"SQL",aliases:["sql"]},{label:"Power BI",aliases:["power bi","powerbi"]},{label:"Data analysis",aliases:["data analysis","analyse de donnees","data analyst","analyse des donnees"]},{label:"Data science",aliases:["data science","data scientist","machine learning","modelisation predictive"]},{label:"AWS",aliases:["aws","amazon web services"]},{label:"Azure",aliases:["azure"]},{label:"Cloud",aliases:["cloud computing","architecture cloud","migration cloud"]},{label:"Cybersécurité",aliases:["cybersecurite","cyber security","securite informatique","soc analyst","siem"]},{label:"Docker",aliases:["docker"]},{label:"Kubernetes",aliases:["kubernetes"]},{label:"Figma",aliases:["figma"]},{label:"SaaS B2B",aliases:["saas b2b","logiciel saas"]},{label:"SAP",aliases:["sap"]},{label:"ERP",aliases:["erp","enterprise resource planning"]},
// Commercial, relation client, marketing, communication
{label:"Développement commercial",aliases:["developpement commercial","business development","business developer","developper le portefeuille","developpement de portefeuille"]},{label:"Prospection B2B",aliases:["prospection b2b","prospection commerciale","cold calling","cold emailing","prise de rendez-vous"]},{label:"Vente complexe",aliases:["vente complexe","cycle de vente complexe","vente consultative","consultative selling"]},{label:"Négociation commerciale",aliases:["negociation commerciale","negocier les contrats","negociation de contrats","negociation client"]},{label:"Grands comptes",aliases:["grands comptes","key account","key account manager","kam","comptes strategiques"]},{label:"Account management",aliases:["account manager","gestion de comptes clients","gestion de portefeuille clients","customer account"]},{label:"Customer Success",aliases:["customer success","customer success manager","cs manager","succes client"]},{label:"Service client",aliases:["service client","relation client","support client","satisfaction client"]},{label:"CRM",aliases:["crm"]},{label:"Salesforce",aliases:["salesforce"]},{label:"HubSpot",aliases:["hubspot"]},{label:"Marketing automation",aliases:["marketing automation","automation marketing","lead nurturing","lead scoring"]},{label:"Marketing digital",aliases:["marketing digital","digital marketing","webmarketing","acquisition digitale"]},{label:"SEO",aliases:["seo","referencement naturel"]},{label:"SEA / Paid media",aliases:["sea","paid media","paid acquisition","google ads","adwords"]},{label:"GEO",aliases:["generative engine optimization","optimisation geo"]},{label:"Content marketing",aliases:["content marketing","strategie de contenu","marketing de contenu"]},{label:"Communication",aliases:["communication corporate","communication interne","communication externe","relations presse"]},{label:"Community management",aliases:["community manager","community management","animation des reseaux sociaux"]},{label:"Événementiel",aliases:["evenementiel","organisation d evenements","event management"]},
// RH, recrutement, formation
{label:"Recrutement",aliases:["recrutement","recruitment","recruteur","recruteuse","talent acquisition"]},{label:"Sourcing candidats",aliases:["sourcing candidats","sourcing de candidats","chasse de tete","approche directe"]},{label:"Entretiens de recrutement",aliases:["entretien de recrutement","entretiens de recrutement","conduite d entretiens","evaluation des candidats"]},{label:"Gestion des talents",aliases:["gestion des talents","talent management","gestion des carrieres","people review"]},{label:"Administration du personnel",aliases:["administration du personnel","gestion administrative du personnel","adp"]},{label:"Paie",aliases:["gestion de la paie","gestionnaire de paie","payroll"]},{label:"Droit social",aliases:["droit social","relations sociales","legislation sociale"]},{label:"Formation",aliases:["ingenierie de formation","formation professionnelle","conception de formation","animation de formation"]},{label:"Conduite du changement",aliases:["conduite du changement","accompagnement au changement","change management"]},
// Finance, comptabilité, audit, banque, assurance
{label:"Comptabilité générale",aliases:["comptabilite generale","comptable general","comptable generale","general ledger"]},{label:"Comptabilité fournisseurs",aliases:["comptabilite fournisseurs","comptable fournisseurs","accounts payable"]},{label:"Comptabilité clients",aliases:["comptabilite clients","comptable clients","accounts receivable"]},{label:"Contrôle de gestion",aliases:["controle de gestion","controleur de gestion","controleuse de gestion","management control"]},{label:"FP&A",aliases:["fp&a","financial planning and analysis","planification financiere"]},{label:"Audit financier",aliases:["audit financier","auditeur financier","auditrice financiere","financial audit"]},{label:"Consolidation",aliases:["consolidation financiere","consolideur","consolidation des comptes"]},{label:"Trésorerie",aliases:["tresorerie","cash management","tresorier","tresoriere"]},{label:"Fiscalité",aliases:["fiscalite","fiscaliste","tax management"]},{label:"Analyse financière",aliases:["analyse financiere","analyste financier","financial analyst"]},{label:"Crédit",aliases:["analyse credit","analyste credit","risque credit","credit management"]},{label:"Assurance",aliases:["souscription assurance","gestion de sinistres","assurance iard","assurance vie"]},{label:"Conformité / Compliance",aliases:["compliance","conformite reglementaire","aml","kyc","lcb-ft"]},{label:"Gestion des risques",aliases:["gestion des risques","risk management","risk manager"]},
// Juridique
{label:"Droit des affaires",aliases:["droit des affaires","juriste affaires","juriste droit des affaires"]},{label:"Droit des contrats",aliases:["droit des contrats","contract management","juriste contrats","contract lawyer"]},{label:"Droit des sociétés",aliases:["droit des societes","corporate law","juriste corporate"]},{label:"Droit du travail",aliases:["droit du travail","juriste droit social","employment law"]},{label:"Protection des données / RGPD",aliases:["rgpd","gdpr","protection des donnees","data protection","dpo"]},{label:"Propriété intellectuelle",aliases:["propriete intellectuelle","droit des marques","droit d auteur","intellectual property"]},
// Achats, supply chain, logistique
{label:"Achats",aliases:["acheteur","acheteuse","achats indirects","achats directs","purchasing","procurement"]},{label:"Négociation fournisseurs",aliases:["negociation fournisseurs","negociation fournisseur","supplier negotiation"]},{label:"Appels d'offres",aliases:["appel d offres","appels d offres","tender management","reponse aux appels d offres"]},{label:"Supply chain",aliases:["supply chain","chaine logistique","supply planning"]},{label:"Logistique",aliases:["logistique","responsable logistique","logisticien","logisticienne"]},{label:"Gestion des stocks",aliases:["gestion des stocks","stock management","inventory management"]},{label:"Approvisionnement",aliases:["approvisionnement","approvisionneur","approvisionneuse","supply planner"]},{label:"Transport",aliases:["gestion du transport","transport routier","transport international","affretement"]},{label:"Planification",aliases:["planification","ordonnancement","planning de production","demand planning"]},
// Industrie, ingénierie, qualité
{label:"Production industrielle",aliases:["production industrielle","responsable production","gestion de production","atelier de production"]},{label:"Maintenance industrielle",aliases:["maintenance industrielle","technicien de maintenance","technicienne de maintenance","responsable maintenance"]},{label:"Méthodes / Industrialisation",aliases:["industrialisation","ingenieur methodes","ingenieure methodes","methodes industrielles"]},{label:"Amélioration continue",aliases:["amelioration continue","lean management","lean manufacturing","kaizen","six sigma"]},{label:"Qualité",aliases:["management de la qualite","assurance qualite","controle qualite","responsable qualite"]},{label:"HSE / QHSE",aliases:["qhse","hse","sante securite environnement","qualite hygiene securite environnement"]},{label:"CAO / DAO",aliases:["cao","dao","autocad","solidworks","catia"]},{label:"Électronique",aliases:["electronique","ingenieur electronique","conception electronique"]},{label:"Électrotechnique",aliases:["electrotechnique","electromecanique","electricite industrielle"]},
// BTP, immobilier
{label:"Conduite de travaux",aliases:["conduite de travaux","conducteur de travaux","conductrice de travaux"]},{label:"Gestion de chantier",aliases:["chef de chantier","cheffe de chantier","gestion de chantier","suivi de chantier"]},{label:"Études de prix",aliases:["etudes de prix","etude de prix","economiste de la construction","chiffrage btp"]},{label:"BIM",aliases:["bim","building information modeling","revit"]},{label:"Immobilier",aliases:["transaction immobiliere","gestion immobiliere","property management","asset management immobilier"]},{label:"Gestion locative",aliases:["gestion locative","property manager","administrateur de biens"]},
// Santé, médico-social
{label:"Soins infirmiers",aliases:["soins infirmiers","infirmier diplome","infirmiere diplomee","ide"]},{label:"Aide-soignant",aliases:["aide-soignant","aide soignant","aide-soignante","aide soignante"]},{label:"Aide à domicile",aliases:["aide a domicile","auxiliaire de vie","assistant de vie","assistante de vie"]},{label:"Coordination des soins",aliases:["coordination des soins","parcours de soins","coordonnateur de soins","coordinatrice de soins"]},{label:"Médico-social",aliases:["medico-social","medicosocial","ehpad","ime","mas"]},{label:"Pharmacie",aliases:["pharmacien","pharmacienne","pharmacie hospitaliere","officine"]},{label:"Affaires réglementaires santé",aliases:["affaires reglementaires","regulatory affairs","materiovigilance","pharmacovigilance"]},
// Hôtellerie, restauration, tourisme, retail
{label:"Hôtellerie",aliases:["hotellerie","reception hotel","receptionniste hotel","front office hotel"]},{label:"Restauration",aliases:["restauration","service en salle","chef de rang","maitre d hotel"]},{label:"Cuisine",aliases:["cuisinier","cuisiniere","chef de cuisine","commis de cuisine"]},{label:"Revenue management",aliases:["revenue management","revenue manager","yield management"]},{label:"Tourisme",aliases:["tourisme","agence de voyage","tour operator","forfaitiste"]},{label:"Retail",aliases:["retail","commerce de detail","responsable de magasin","directeur de magasin","directrice de magasin"]},{label:"Merchandising",aliases:["merchandising","visual merchandising","category management"]},
// Administration, office, service public
{label:"Assistanat de direction",aliases:["assistant de direction","assistante de direction","executive assistant"]},{label:"Office management",aliases:["office manager","office management","gestion de bureau"]},{label:"Gestion administrative",aliases:["gestion administrative","suivi administratif","administration generale"]},{label:"Marchés publics",aliases:["marches publics","commande publique","public procurement"]},
// Compétences transversales explicites
{label:"Gestion de projet",aliases:["gestion de projet","project management","chef de projet","cheffe de projet","pilotage de projet"]},{label:"Management d'équipe",aliases:["management d equipe","management equipe","manager une equipe","encadrement d equipe","pilotage d equipe"]},{label:"Gestion budgétaire",aliases:["gestion budgetaire","gestion de budget","suivi budgetaire","budget management"]},{label:"Reporting / KPI",aliases:["reporting","tableaux de bord","tableau de bord","kpi","indicateurs de performance"]},{label:"Anglais professionnel",aliases:["anglais professionnel","anglais courant","anglais fluent","english professional","professional english","fluent english"]}
];
const NEGATION_PATTERNS=[/aucune?\s+(?:experience|pratique|maitrise)/,/pas\s+d\s+(?:experience|expertise|pratique)/,/sans\s+(?:experience|expertise|pratique|maitrise)/,/experience\s+(?:limitee|faible|minimale)/,/notions?\s+(?:seulement|uniquement)/,/(?:non|peu)\s+(?:maitrise|experimente|experimentee|operationnel|operationnelle)/,/veille\s+(?:sur|autour de)/];
function isWordChar(ch:string|undefined){return !!ch&&/[a-z0-9]/i.test(ch)}
function occurrences(text:string,needle:string){const out:number[]=[];let start=0;while(true){const i=text.indexOf(needle,start);if(i<0)break;const before=text[i-1],after=text[i+needle.length];if(!isWordChar(before)&&!isWordChar(after))out.push(i);start=i+Math.max(1,needle.length)}return out}
export function aliasEvidence(rawText:string,aliasRaw:string){const text=` ${normalize(rawText)} `;const alias=normalize(aliasRaw);if(!alias)return{positive:false,negated:false};const hits=occurrences(text,alias);if(!hits.length)return{positive:false,negated:false};let negated=false;for(const idx of hits){const before=text.slice(Math.max(0,idx-90),idx);const after=text.slice(idx+alias.length,Math.min(text.length,idx+alias.length+55));if(NEGATION_PATTERNS.some(p=>p.test(`${before} ${after}`)))negated=true;else return{positive:true,negated}}return{positive:false,negated}}
export function detectSkills(rawText:string){return SKILL_GROUPS.filter(({aliases})=>aliases.some(a=>aliasEvidence(rawText,a).positive)).map(x=>x.label)}
export function detectNegatedSkills(rawText:string){return SKILL_GROUPS.filter(({aliases})=>{const e=aliases.map(a=>aliasEvidence(rawText,a));return e.some(x=>x.negated)&&!e.some(x=>x.positive)}).map(x=>x.label)}
function cleanLine(s:string){return s.replace(/[•|]+/g," ").replace(/\s+/g," ").trim()}
function looksLikeName(s:string){const x=cleanLine(s);if(x.length<4||x.length>70||/@|https?:|www\.|\d{4,}/i.test(x))return false;const words=x.split(/\s+/);if(words.length<2||words.length>5)return false;return words.every(w=>/^[A-Za-zÀ-ÖØ-öø-ÿ'’-]+$/.test(w))}
function extractName(raw:string,email:string){const lines=raw.split(/\r?\n/).map(cleanLine).filter(Boolean).slice(0,18);const direct=lines.find(looksLikeName);if(direct)return direct;if(email){const local=email.split("@")[0].replace(/[._-]+/g," ");if(local.split(" ").length>=2)return local.replace(/\b\w/g,c=>c.toUpperCase())}return "Candidat importé"}
function extractLocation(raw:string){const lines=raw.split(/\r?\n/).map(cleanLine).filter(Boolean).slice(0,25);for(const line of lines){const m=line.match(/(?:localisation|location|ville|adresse)\s*[:\-]\s*([^|•,]{2,60})/i);if(m)return cleanLine(m[1]);}const known=["Paris","Lyon","Marseille","Toulouse","Bordeaux","Lille","Nantes","Strasbourg","Rennes","Montpellier","Boulogne-Billancourt","Levallois-Perret","Versailles","Antony","Metz"];for(const city of known)if(new RegExp(`\\b${city.replace("-","[- ]")}\\b`,"i").test(lines.join(" ")))return city;return ""}
function estimateYearsFromRanges(raw:string){
 const currentYear=new Date().getFullYear();const ranges=[...raw.matchAll(/\b(19\d{2}|20\d{2})\s*[-–—]\s*(19\d{2}|20\d{2}|present|présent|aujourd'hui|aujourd’hui|current)\b/gi)];
 if(!ranges.length)return null;const intervals=ranges.map(m=>{const start=Number(m[1]);const end=/^\d{4}$/.test(m[2])?Number(m[2]):currentYear;return[start,Math.max(start,Math.min(end,currentYear))] as [number,number]}).filter(([s,e])=>s>=1980&&e>=s&&e-s<=20);
 if(!intervals.length)return null;intervals.sort((a,b)=>a[0]-b[0]);const merged:[number,number][]=[];for(const it of intervals){const last=merged[merged.length-1];if(!last||it[0]>last[1])merged.push([...it] as [number,number]);else last[1]=Math.max(last[1],it[1]);}const total=merged.reduce((sum,[s,e])=>sum+(e-s),0);return total>0?Math.min(45,total):null;
}
export function extractCandidate(rawText:string){const compact=rawText.replace(/\s+/g," ").trim();const email=compact.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]??"";const yearsMatches=[...compact.matchAll(/(\d{1,2})\s*(?:ans|annees|années)\s+(?:d['’]?experience|d’expérience|d'experience)/gi)].map(m=>Number(m[1])).filter(Number.isFinite);const explicitYears=yearsMatches.length?Math.max(...yearsMatches):null;const rangeYears=estimateYearsFromRanges(rawText);const years=explicitYears??rangeYears;const skills=detectSkills(compact);const summary=compact.length>650?compact.slice(0,650)+"…":compact;return{fullName:extractName(rawText,email),location:extractLocation(rawText),email,years,skills,summary}}