"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";

type Template={id:string;type:string;name:string;subject:string;body:string;active:boolean};
type Webhook={id:string;name:string;url:string;events:string;active:boolean};
const labels:Record<string,string>={RECEIPT:"Accusé de réception",CONTACT:"Prise de contact",FOLLOW_UP:"Relance",INTERVIEW:"Proposition d'entretien",POST_INTERVIEW:"Suivi post-entretien"};
const defaults:Record<string,{subject:string;body:string}>={
 RECEIPT:{subject:"Votre candidature — {{mission}}",body:"Bonjour {{candidate}},\n\nNous avons bien reçu votre candidature concernant {{mission}}. Votre profil est en cours d'analyse par notre équipe.\n\nBien cordialement,\n{{recruiter}}"},
 CONTACT:{subject:"Échange concernant {{mission}}",body:"Bonjour {{candidate}},\n\nVotre parcours retient notre attention pour la mission {{mission}}. Je souhaiterais échanger avec vous afin de valider quelques éléments et votre intérêt.\n\nBien cordialement,\n{{recruiter}}"},
 FOLLOW_UP:{subject:"Suivi — {{mission}}",body:"Bonjour {{candidate}},\n\nJe reviens vers vous concernant la mission {{mission}}. N'hésitez pas à me confirmer vos disponibilités pour poursuivre nos échanges.\n\nBien cordialement,\n{{recruiter}}"},
 INTERVIEW:{subject:"Proposition d'entretien — {{mission}}",body:"Bonjour {{candidate}},\n\nJe vous propose un entretien afin d'échanger plus précisément sur la mission {{mission}} et votre parcours.\n\nBien cordialement,\n{{recruiter}}"},
 POST_INTERVIEW:{subject:"Suite à notre entretien — {{mission}}",body:"Bonjour {{candidate}},\n\nMerci pour notre échange concernant {{mission}}. Nous revenons vers vous dès que possible avec la prochaine étape du processus.\n\nBien cordialement,\n{{recruiter}}"}
};

export default function AutomationSettings({sla,templates,webhooks}:{sla:{candidate:number;interview:number;client:number};templates:Template[];webhooks:Webhook[]}){
 const router=useRouter();const[saving,setSaving]=useState("");
 const[values,setValues]=useState({candidate:sla.candidate,interview:sla.interview,client:sla.client});
 const map=Object.fromEntries(templates.map(t=>[t.type,t]));
 const[forms,setForms]=useState<Record<string,{name:string;subject:string;body:string}>>(()=>Object.fromEntries(Object.keys(labels).map(type=>{const t=map[type];return[type,{name:t?.name||labels[type],subject:t?.subject||defaults[type].subject,body:t?.body||defaults[type].body}]})));
 const[hook,setHook]=useState({name:"",url:"",events:"candidate.activity.validated"});
 async function post(payload:any,key:string){setSaving(key);const res=await fetch("/api/admin/automation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setSaving("");const d=await res.json().catch(()=>({}));if(!res.ok)return alert(d.error||"Enregistrement impossible");router.refresh()}
 return <>
  <div className="card"><h2>SLA relationnels</h2><p className="muted">Définis les délais de référence. Ils servent à signaler les dossiers à risque ; ils n'envoient rien automatiquement.</p><div className="criteriaGrid"><div><label>Réponse candidat (heures)<input type="number" min="1" value={values.candidate} onChange={e=>setValues(v=>({...v,candidate:Number(e.target.value)}))}/></label></div><div><label>Suivi après entretien (heures)<input type="number" min="1" value={values.interview} onChange={e=>setValues(v=>({...v,interview:Number(e.target.value)}))}/></label></div><div><label>Retour client / relance (heures)<input type="number" min="1" value={values.client} onChange={e=>setValues(v=>({...v,client:Number(e.target.value)}))}/></label></div></div><button className="btn" disabled={saving==="sla"} onClick={()=>post({op:"sla",candidateResponseSlaHours:values.candidate,interviewFollowupSlaHours:values.interview,clientFeedbackSlaHours:values.client},"sla")}>{saving==="sla"?"Enregistrement…":"Enregistrer les SLA"}</button></div>
  <div className="card" style={{marginTop:16}}><h2>Modèles relationnels du cabinet</h2><p className="muted">Variables disponibles : <code>{"{{candidate}}"}</code>, <code>{"{{mission}}"}</code>, <code>{"{{client}}"}</code>, <code>{"{{recruiter}}"}</code>. Les messages restent modifiables avant toute action.</p>{Object.keys(labels).map(type=>{const f=forms[type];return <details className="opsDetails" key={type}><summary>{labels[type]}</summary><div className="field"><label>Nom<input value={f.name} onChange={e=>setForms(x=>({...x,[type]:{...x[type],name:e.target.value}}))}/></label></div><div className="field"><label>Objet<input value={f.subject} onChange={e=>setForms(x=>({...x,[type]:{...x[type],subject:e.target.value}}))}/></label></div><div className="field"><label>Message<textarea rows={7} value={f.body} onChange={e=>setForms(x=>({...x,[type]:{...x[type],body:e.target.value}}))}/></label></div><button className="btn secondary" disabled={saving===type} onClick={()=>post({op:"template",type,...f},type)}>{saving===type?"Enregistrement…":"Enregistrer ce modèle"}</button></details>})}</div>
  <div className="card" style={{marginTop:16}}><h2>Connecteurs génériques / Webhooks</h2><p className="muted">Host Talent AI peut transmettre une action validée vers un outil externe (ATS, CRM, Microsoft 365, n8n, Make, téléphonie…). Aucune transmission n'est automatique : elle doit être déclenchée explicitement par le recruteur.</p><div className="criteriaGrid"><div><label>Nom<input value={hook.name} onChange={e=>setHook({...hook,name:e.target.value})} placeholder="Ex. ATS cabinet"/></label></div><div><label>URL HTTPS<input value={hook.url} onChange={e=>setHook({...hook,url:e.target.value})} placeholder="https://..."/></label></div><div><label>Événements<input value={hook.events} onChange={e=>setHook({...hook,events:e.target.value})}/></label></div></div><button className="btn" disabled={saving==="hook"} onClick={()=>post({op:"webhook_create",...hook},"hook")}>Ajouter le connecteur</button><div style={{marginTop:18}}>{webhooks.length===0?<p className="muted">Aucun connecteur configuré.</p>:webhooks.map(w=><div className="listRow" key={w.id}><div><strong>{w.name}</strong><div className="muted small">{w.url} · {w.events} · {w.active?"actif":"désactivé"}</div></div><div className="actions"><button className="btn secondary" onClick={()=>post({op:"webhook_toggle",id:w.id},`toggle-${w.id}`)}>{w.active?"Désactiver":"Activer"}</button><button className="btn secondary" onClick={()=>confirm("Supprimer ce connecteur ?")&&post({op:"webhook_delete",id:w.id},`delete-${w.id}`)}>Supprimer</button></div></div>)}</div></div>
 </>;
}
