import Link from "next/link";
import {prisma} from "../lib/db";
import {requireUser} from "../lib/auth";
import {buildTalentObservatory} from "../lib/talentTrends";
import {getTalentHistory,recordTalentSnapshot} from "../lib/talentHistory";
import {ComparisonBars} from "../components/InsightCharts";
export const dynamic="force-dynamic";

function tensionClass(t:string){return t==="Forte"?"warningText":t==="Modérée"?"scoreMini":t==="Abondance"?"successText":"muted"}
function changeLabel(v:number|null){if(v===null)return"nouveau";if(v===0)return"stable";return`${v>0?"+":""}${v}%`}
function changeClass(v:number|null){if(v===null)return"scoreMini";if(v>0)return"warningText";if(v<0)return"successText";return"muted"}
export default async function TalentObservatory(){
 const user=await requireUser();
 const [candidates,jobs]=await Promise.all([
  prisma.candidate.findMany({where:{organizationId:user.organizationId},select:{id:true,skills:true,rawText:true,experienceYears:true,location:true,createdAt:true,matches:{where:{organizationId:user.organizationId},select:{score:true,job:{select:{id:true,title:true,mustHave:true,shouldHave:true}}}}}}),
  prisma.job.findMany({where:{organizationId:user.organizationId},select:{id:true,title:true,mustHave:true,shouldHave:true,optional:true,createdAt:true}})
 ]);
 const t=buildTalentObservatory(candidates,jobs);
 await recordTalentSnapshot(user.organizationId,t);
 const history=await getTalentHistory(user.organizationId,t.market);
 const activeTrend=history.trend30.available?history.trend30:history.trend90.available?history.trend90:null;
 const demandVsQualified=t.market.filter(x=>x.demand>0).slice(0,10).map(x=>({label:x.name,primary:x.demand,secondary:x.qualified,meta:`${x.tension} · ${x.ratio} qualifié(s)/mission`}));
 return <>
  <div className="hero"><div><div className="eyebrow">V2.7 · OBSERVATOIRE TALENT</div><h1>Comprendre le marché interne du cabinet.</h1><p className="muted">L'Observatoire Talent croise les CV, les missions et les matchings pour mesurer la disponibilité réelle des compétences, repérer les tensions et identifier le potentiel sous-exploité du vivier.</p></div><div className="actions"><Link className="btn secondary" href="/market">Observatoire général</Link><Link className="btn secondary" href="/candidates">Vivier</Link><Link className="btn secondary" href="/jobs">Missions</Link></div></div>

  {t.matchCoverage<90&&<div className="card" style={{marginBottom:20}}><strong className="warningText">Analyse provisoire · matching {t.matchCoverage}% couvert</strong><p className="muted" style={{marginBottom:0}}>Les indicateurs de tension deviennent fiables lorsque le recalcul candidat × mission est terminé. Les volumes bruts restent utilisables.</p></div>}

  <div className="kpiGrid"><div className="card kpiCard"><div className="muted">Candidats analysés</div><div className="score">{t.candidateCount}</div></div><div className="card kpiCard"><div className="muted">Missions analysées</div><div className="score">{t.jobCount}</div></div><div className="card kpiCard"><div className="muted">Compétences / familles</div><div className="score">{t.skillCount}</div></div><div className="card kpiCard"><div className="muted">Tensions détectées</div><div className="score">{t.tensions.length}</div></div><div className="card kpiCard"><div className="muted">Jours historisés</div><div className="score">{history.historyDays}</div><div className="small muted">{history.snapshotCount} snapshot(s)</div></div></div>

  <ComparisonBars title="Demande vs offre qualifiée" description="Pour chaque compétence, compare le nombre de missions concernées au nombre de candidats ayant un matching ≥ 70 sur au moins une mission correspondante." items={demandVsQualified}/>

  <div className="card sectionCard"><div className="sectionHeader"><div><h2>Tension du marché interne</h2><p className="muted">Ratio = candidats qualifiés (score ≥ 70 sur une mission concernée) ÷ missions demandant la compétence.</p></div></div><div className="tableWrap"><table><thead><tr><th>Compétence / famille</th><th>Demande</th><th>Offre brute</th><th>Offre qualifiée</th><th>Qualifiés / mission</th><th>Tension</th></tr></thead><tbody>{t.market.filter(x=>x.demand>0).slice(0,20).map(x=><tr key={x.name}><td><strong>{x.name}</strong></td><td>{x.demand}</td><td>{x.supply}</td><td>{x.qualified}</td><td>{x.ratio}</td><td className={tensionClass(x.tension)}><strong>{x.tension}</strong></td></tr>)}</tbody></table></div><details className="opsDetails"><summary>Comprendre l'indice de tension</summary><p className="muted">Forte : moins de 1 candidat qualifié par mission. Modérée : de 1 à moins de 2. Équilibrée : de 2 à 4. Abondance : plus de 4. L'absence de preuve dans un CV ne signifie pas incompatibilité : l'indice mesure uniquement les informations structurées et les matchings disponibles.</p></details></div>

  <div className="grid sectionGrid"><div className="card"><h2>Écarts vivier ↔ missions</h2><p className="muted">Besoins les moins couverts par des candidats réellement compatibles.</p>{t.gaps.slice(0,8).map(x=><div className="listRow" key={x.name}><div><strong>{x.name}</strong><div className="small muted">{x.demand} mission(s) · {x.qualified} qualifié(s) · {x.supply} brut(s)</div></div><span className={tensionClass(x.tension)}>{x.tension}</span></div>)}</div><div className="card"><h2>Potentiel sous-exploité</h2><p className="muted">Compétences présentes chez plusieurs candidats mais absentes des besoins actuellement structurés.</p>{t.underused.length?t.underused.map(x=><div className="listRow" key={x.name}><strong>{x.name}</strong><span>{x.supply} CV</span></div>):<p className="muted">Aucun signal significatif avec le vivier actuel.</p>}</div></div>

  <div className="card sectionCard"><div className="sectionHeader"><div><h2>Signaux de l'Observatoire Talent</h2><p className="muted">Constats déterministes issus uniquement des données internes du cabinet.</p></div></div>{t.signals.length?t.signals.map((s,i)=><div className="signalRow" key={`${s.title}-${i}`}><div><strong>{s.title}</strong><p className="muted">{s.detail}</p><p className="small"><strong>Action suggérée :</strong> {s.action}</p></div></div>):<p className="muted">Aucun signal prioritaire détecté.</p>}</div>

  <div className="card sectionCard"><div className="sectionHeader"><div><h2>Compétences en mouvement</h2><p className="muted">Comparaison entre le snapshot actuel et le dernier état disponible au moins 30 jours auparavant, puis 90 jours lorsque l'historique le permet.</p></div></div>{activeTrend?<div className="tableWrap"><table><thead><tr><th>Compétence</th><th>Demande actuelle</th><th>Variation demande</th><th>Offre actuelle</th><th>Variation offre</th><th>Qualifiés</th></tr></thead><tbody>{activeTrend.rows.slice(0,15).map(x=><tr key={x.name}><td><strong>{x.name}</strong></td><td>{x.demand}</td><td className={changeClass(x.demandChange)}><strong>{changeLabel(x.demandChange)}</strong></td><td>{x.supply}</td><td>{changeLabel(x.supplyChange)}</td><td>{x.qualified} <span className="small muted">({changeLabel(x.qualifiedChange)})</span></td></tr>)}</tbody></table><p className="small muted">Fenêtre utilisée : {activeTrend.period} jours · base du {activeTrend.baseDate.toLocaleDateString("fr-FR")}.</p></div>:<div className="historyEmpty"><strong>Historique en cours de constitution.</strong><p className="muted">Le snapshot du jour est enregistré automatiquement. Les premières variations fiables apparaîtront après 30 jours d'historique réel ; Host Talent AI n'effectue aucun rétro-calcul artificiel.</p><div className="historyProgress"><span style={{width:`${Math.min(100,Math.round(history.historyDays/30*100))}%`}}/></div><p className="small muted">{history.historyDays}/30 jours constitués · {history.snapshotCount} snapshot(s) enregistré(s).</p></div>}</div>

  <div className="grid sectionGrid"><div className="card"><h2>Structure du vivier</h2><div className="listRow"><span>Expérience moyenne</span><strong>{t.averageExperience??"—"}{t.averageExperience!=null?" ans":""}</strong></div><div className="listRow"><span>Junior · &lt; 3 ans</span><strong>{t.seniority.junior}</strong></div><div className="listRow"><span>Confirmé · 3–6 ans</span><strong>{t.seniority.confirmed}</strong></div><div className="listRow"><span>Senior · ≥ 7 ans</span><strong>{t.seniority.senior}</strong></div><div className="listRow"><span>À confirmer</span><strong>{t.seniority.unknown}</strong></div></div><div className="card"><h2>Mémoire de l'Observatoire</h2><p className="muted">Un snapshot est conservé au maximum une fois par jour et par organisation. Il contient uniquement des agrégats du vivier et des missions.</p><div className="listRow"><span>Premier snapshot</span><strong>{history.firstSnapshotDate?history.firstSnapshotDate.toLocaleDateString("fr-FR"):"Aujourd'hui"}</strong></div><div className="listRow"><span>Snapshots disponibles</span><strong>{history.snapshotCount}</strong></div><div className="listRow"><span>Fenêtre 30 jours</span><strong>{history.trend30.available?"Disponible":"En constitution"}</strong></div><div className="listRow"><span>Fenêtre 90 jours</span><strong>{history.trend90.available?"Disponible":"En constitution"}</strong></div></div></div>

  <div className="card sectionCard"><h2>Méthodologie</h2><p className="muted">Cet Observatoire décrit uniquement le micro-marché du cabinet à partir des CV, missions, matchings et snapshots agrégés. Pour les tendances générales de l'emploi et les pistes de nouveaux marchés, utilisez l’Observatoire général. Une compétence absente d'un CV peut simplement ne pas y être explicitée ; les métriques servent à prioriser la revue humaine, le sourcing et la stratégie commerciale.</p><Link className="btn secondary" href="/market">Ouvrir l’Observatoire général</Link></div>
 </>;
}
