import Link from "next/link";
import {prisma} from "../lib/db";
import {requireUser} from "../lib/auth";
import {buildTalentObservatory} from "../lib/talentTrends";
export const dynamic="force-dynamic";

function tensionClass(t:string){return t==="Forte"?"warningText":t==="Modérée"?"scoreMini":t==="Abondance"?"successText":"muted"}
export default async function TalentObservatory(){
 const user=await requireUser();
 const [candidates,jobs]=await Promise.all([
  prisma.candidate.findMany({where:{organizationId:user.organizationId},select:{id:true,skills:true,rawText:true,experienceYears:true,location:true,createdAt:true,matches:{where:{organizationId:user.organizationId},select:{score:true,job:{select:{id:true,title:true,mustHave:true,shouldHave:true}}}}}}),
  prisma.job.findMany({where:{organizationId:user.organizationId},select:{id:true,title:true,mustHave:true,shouldHave:true,optional:true,createdAt:true}})
 ]);
 const t=buildTalentObservatory(candidates,jobs);
 return <>
  <div className="hero"><div><div className="eyebrow">V2.7 · OBSERVATOIRE TALENT</div><h1>Observer les déséquilibres du marché du cabinet.</h1><p className="muted">L'Observatoire croise la demande des missions, l'offre du vivier et les matchings pour distinguer disponibilité brute et disponibilité réellement qualifiée.</p></div><div className="actions"><Link className="btn secondary" href="/candidates">Vivier</Link><Link className="btn secondary" href="/jobs">Missions</Link></div></div>

  {t.matchCoverage<90&&<div className="card" style={{marginBottom:20}}><strong className="warningText">Analyse provisoire · matching {t.matchCoverage}% couvert</strong><p className="muted" style={{marginBottom:0}}>Les indicateurs de tension deviennent fiables lorsque le recalcul candidat × mission est terminé. Les volumes bruts restent utilisables.</p></div>}

  <div className="kpiGrid"><div className="card kpiCard"><div className="muted">Candidats analysés</div><div className="score">{t.candidateCount}</div></div><div className="card kpiCard"><div className="muted">Missions analysées</div><div className="score">{t.jobCount}</div></div><div className="card kpiCard"><div className="muted">Compétences / familles</div><div className="score">{t.skillCount}</div></div><div className="card kpiCard"><div className="muted">Tensions détectées</div><div className="score">{t.tensions.length}</div></div><div className="card kpiCard"><div className="muted">Signaux actifs</div><div className="score">{t.signals.length}</div></div></div>

  <div className="card sectionCard"><div className="sectionHeader"><div><h2>Tension du marché interne</h2><p className="muted">Ratio = candidats qualifiés (score ≥ 70 sur une mission concernée) ÷ missions demandant la compétence.</p></div></div><div className="tableWrap"><table><thead><tr><th>Compétence / famille</th><th>Demande</th><th>Offre brute</th><th>Offre qualifiée</th><th>Qualifiés / mission</th><th>Tension</th></tr></thead><tbody>{t.market.filter(x=>x.demand>0).slice(0,20).map(x=><tr key={x.name}><td><strong>{x.name}</strong></td><td>{x.demand}</td><td>{x.supply}</td><td>{x.qualified}</td><td>{x.ratio}</td><td className={tensionClass(x.tension)}><strong>{x.tension}</strong></td></tr>)}</tbody></table></div><details className="opsDetails"><summary>Comprendre l'indice de tension</summary><p className="muted">Forte : moins de 1 candidat qualifié par mission. Modérée : de 1 à moins de 2. Équilibrée : de 2 à 4. Abondance : plus de 4. L'absence de preuve dans un CV ne signifie pas incompatibilité : l'indice mesure uniquement les informations structurées et les matchings disponibles.</p></details></div>

  <div className="grid sectionGrid"><div className="card"><h2>Écarts vivier ↔ missions</h2><p className="muted">Besoins les moins couverts par des candidats réellement compatibles.</p>{t.gaps.slice(0,8).map(x=><div className="listRow" key={x.name}><div><strong>{x.name}</strong><div className="small muted">{x.demand} mission(s) · {x.qualified} qualifié(s) · {x.supply} brut(s)</div></div><span className={tensionClass(x.tension)}>{x.tension}</span></div>)}</div><div className="card"><h2>Potentiel sous-exploité</h2><p className="muted">Compétences présentes chez plusieurs candidats mais absentes des besoins actuellement structurés.</p>{t.underused.length?t.underused.map(x=><div className="listRow" key={x.name}><strong>{x.name}</strong><span>{x.supply} CV</span></div>):<p className="muted">Aucun signal significatif avec le vivier actuel.</p>}</div></div>

  <div className="card sectionCard"><div className="sectionHeader"><div><h2>Signaux de l'Observatoire</h2><p className="muted">Constats déterministes issus des données internes. Aucun signal n'est une décision automatique.</p></div></div>{t.signals.length?t.signals.map((s,i)=><div className="signalRow" key={`${s.title}-${i}`}><div><strong>{s.title}</strong><p className="muted">{s.detail}</p><p className="small"><strong>Action suggérée :</strong> {s.action}</p></div></div>):<p className="muted">Aucun signal prioritaire détecté.</p>}</div>

  <div className="grid sectionGrid"><div className="card"><h2>Compétences en mouvement</h2>{t.historySufficient?<><p className="muted">{t.historyDays} jours d'historique sont disponibles. La prochaine couche comparera les fenêtres 30/90 jours.</p><p>Historisation suffisante pour commencer les tendances temporelles.</p></>:<><p className="muted">Historique disponible : {t.historyDays} jour(s).</p><p><strong>Historique insuffisant pour afficher une hausse ou une baisse fiable.</strong></p><p className="small muted">Host Talent AI n'invente donc aucune tendance temporelle. Les évolutions apparaîtront lorsque les données couvriront au moins 30 jours.</p></>}</div><div className="card"><h2>Structure du vivier</h2><div className="listRow"><span>Expérience moyenne</span><strong>{t.averageExperience??"—"}{t.averageExperience!=null?" ans":""}</strong></div><div className="listRow"><span>Junior · &lt; 3 ans</span><strong>{t.seniority.junior}</strong></div><div className="listRow"><span>Confirmé · 3–6 ans</span><strong>{t.seniority.confirmed}</strong></div><div className="listRow"><span>Senior · ≥ 7 ans</span><strong>{t.seniority.senior}</strong></div><div className="listRow"><span>À confirmer</span><strong>{t.seniority.unknown}</strong></div></div></div>

  <div className="card sectionCard"><h2>Méthodologie</h2><p className="muted">Cet Observatoire décrit le micro-marché du cabinet à partir des CV, missions et matchings présents dans Host Talent AI. Il ne représente pas encore le marché externe de l'emploi. Une compétence absente d'un CV peut simplement ne pas y être explicitée ; les métriques servent à prioriser la revue humaine, le sourcing et la stratégie commerciale.</p></div>
 </>;
}
