"use client";

import { useState } from "react";

type Props={surveyToken:string;candidateName:string;jobTitle:string;organizationName:string};

export default function CandidateExperienceForm({surveyToken,candidateName,jobTitle,organizationName}:Props){
 const[clarity,setClarity]=useState(4),[responsiveness,setResponsiveness]=useState(4),[respect,setRespect]=useState(5),[transparency,setTransparency]=useState(4),[recommendation,setRecommendation]=useState(8),[comment,setComment]=useState(""),[saving,setSaving]=useState(false),[done,setDone]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const res=await fetch(`/api/public/experience/${surveyToken}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clarity,responsiveness,respect,transparency,recommendation,comment})});setSaving(false);if(!res.ok){const d=await res.json().catch(()=>({}));return setError(d.error||"Impossible d'enregistrer votre retour.")}setDone(true)}
 if(done)return <div className="card"><div className="eyebrow">MERCI</div><h1>Votre retour a bien été enregistré.</h1><p className="muted">Merci d'avoir pris quelques instants pour partager votre expérience. Ces réponses servent à améliorer le parcours candidat.</p></div>;
 const scale=(label:string,value:number,setter:(v:number)=>void)=><div className="field"><label>{label}<select value={value} onChange={e=>setter(Number(e.target.value))}><option value="1">1 · Très insuffisant</option><option value="2">2 · Insuffisant</option><option value="3">3 · Correct</option><option value="4">4 · Bon</option><option value="5">5 · Excellent</option></select></label></div>;
 return <div className="card"><div className="eyebrow">EXPÉRIENCE CANDIDAT</div><h1>Votre parcours compte.</h1><p className="muted">{organizationName} souhaite améliorer la qualité de son accompagnement autour de la mission « {jobTitle} ». Ce questionnaire concerne votre expérience du processus, pas l'évaluation de votre candidature.</p><form onSubmit={submit}>{scale("Clarté des informations reçues",clarity,setClarity)}{scale("Réactivité et qualité du suivi",responsiveness,setResponsiveness)}{scale("Respect et qualité de la relation",respect,setRespect)}{scale("Transparence sur les prochaines étapes",transparency,setTransparency)}<div className="field"><label>Recommanderiez-vous ce cabinet / cette expérience ?<input type="number" min="0" max="10" value={recommendation} onChange={e=>setRecommendation(Number(e.target.value))}/></label><span className="muted small">0 = pas du tout · 10 = tout à fait</span></div><div className="field"><label>Commentaire facultatif<textarea rows={5} maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Qu'est-ce qui pourrait être amélioré dans votre parcours ?"/></label></div>{error&&<p className="warningText">{error}</p>}<button className="btn" type="submit" disabled={saving}>{saving?"Enregistrement…":"Envoyer mon retour"}</button></form><p className="muted small" style={{marginTop:18}}>Réponse liée à ce parcours de recrutement. Elle est utilisée pour mesurer et améliorer l'expérience candidat.</p></div>;
}
