"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type UserRow={id:string;fullName:string;email:string;role:string;active:boolean};

export default function UserAdminPanel({users,currentUserId}:{users:UserRow[];currentUserId:string}){
 const router=useRouter(); const[form,setForm]=useState({fullName:"",email:"",password:"",role:"RECRUITER"}); const[error,setError]=useState(""); const[loading,setLoading]=useState(false);
 async function createUser(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");const res=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await res.json().catch(()=>({}));if(!res.ok){setError(data.error||"Création impossible");setLoading(false);return;}setForm({fullName:"",email:"",password:"",role:"RECRUITER"});setLoading(false);router.refresh();}
 async function patch(id:string,payload:Record<string,unknown>){const res=await fetch(`/api/admin/users/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!res.ok){const data=await res.json().catch(()=>({}));alert(data.error||"Mise à jour impossible");return;}router.refresh();}
 return <div className="grid adminGrid"><div className="card"><h2>Ajouter un utilisateur</h2><form onSubmit={createUser}><div className="field"><label>Nom complet<input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} required/></label></div><div className="field"><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label></div><div className="field"><label>Mot de passe initial<input type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label></div><div className="field"><label>Rôle<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="RECRUITER">Recruteur</option><option value="ADMIN">Administrateur</option></select></label></div>{error&&<p className="errorText">{error}</p>}<button className="btn" disabled={loading}>{loading?"Création…":"Créer l'utilisateur"}</button></form></div><div className="card"><h2>Utilisateurs du cabinet</h2>{users.map(u=><div className="userRow" key={u.id}><div><strong>{u.fullName}</strong><div className="muted small">{u.email} · {u.role==="ADMIN"?"Administrateur":"Recruteur"}</div></div><div className="actions"><select value={u.role} onChange={e=>patch(u.id,{role:e.target.value})} disabled={u.id===currentUserId}><option value="RECRUITER">Recruteur</option><option value="ADMIN">Administrateur</option></select><button className={`btn ${u.active?"secondary":""}`} onClick={()=>patch(u.id,{active:!u.active})} disabled={u.id===currentUserId}>{u.active?"Désactiver":"Réactiver"}</button></div></div>)}</div></div>;
}
